#!/usr/bin/env python3
"""RETIRED — LooksMenu FaceGen slot-2 overlays never paint (SkinTint-only).

Wound Lab face path now uses Scripted Face Tints (SFT.esp) Damage/Boxer
headparts via DecayFaceOverlays.txt. Kept only as a historical generator for
the unused F4EE pack under Data/F4SE + Data/Materials.

Do not wire this into deploy or MCM.
"""
from __future__ import annotations

import json
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Curated vanilla FaceDetails stems appropriate for corpse / decay look-test.
# Order = MCM iFaceLabTemplate:WoundLab stepper (must stay in sync via tests).
FACE_BANK: list[str] = [
    # Bruises
    "Bruising01",
    "Bruising02",
    "Bruising03",
    "Bruising04",
    # Decay / dirt / illness
    "Sores01",
    "Sores02",
    "Sores03",
    "Sores04",
    "Splochy2",
    "Splochy3",
    "Splochy5",
    "Splochy7",
    "DarkEyeSockets",
    "EyeGaunt",
    "CheekSunkenFemale",
    "GhoulFemaleSplotchy1",
    "GhoulFemaleSplotchy2",
    "GhoulFemaleSplotchy3",
    "CraterFace1",
    "Pocks1",
    "Pocks2",
    # Scars / stitches (subset — full Scar1-21 is too large for MCM)
    "Scar1",
    "Scar2",
    "Scar3",
    "Scar5",
    "Scar8",
    "Scar10",
    "Scar12",
    "Scar15",
    "EyeScar1",
    "Stitches01",
    "Stitches02",
    "Stitches03",
]

# Stems known to ship a matching _n.dds in vanilla FaceDetails.
FACE_HAS_NORMAL: set[str] = {
    "CheekBlemish02",
    "CheekBlemish04",
    "CheekBlemish05",
    "EyeScar1",
    "Pocks1",
    "Pocks2",
    "Scar1",
    "Scar2",
    "Scar3",
    "Scar4",
    "Scar5",
    "Scar6",
    "Scar7",
    "Scar8",
    "Scar9",
    "Scar10",
    "Scar11",
    "Scar12",
    "Scar13",
    "Scar14",
    "Scar15",
    "Scar16",
    "Scar17",
    "Scar18",
    "Scar19",
    "Scar20",
    "Scar21",
    "Sores01",
    "Sores02",
    "Sores03",
    "Sores04",
}

DEFAULT_NORMAL = "Actors/Character/BaseHumanFemale/BaseFemaleHead_n.dds"
FACE_SLOT = 2  # FaceGen Head (F4SE biped index; body=3 hands=4)
FACEDETAILS_DIR = "Actors/Character/Character Assets/FaceDetails"

# Porcupine SkinTexture_01.BGEM binary (BGEM v2) used as a layout template.
# Paths are length-prefixed null-terminated strings; we rewrite those only.
_TEMPLATE_HEX = (
    "4247454d020000000300000000000000000000000000803f0000803f6666663f"
    "01040000000100000040000001010000000000000000000000000000803f"
    "00250000006f7665726c6179732f4a656666657936372f536b696e546578747572655f30312e64647300"
    "01000000000100000000320000004163746f72732f4368617261637465722f6261736568756d616e66656d616c652f66656d616c65626f64795f6e2e64647300"
    "01000000000000000000000000803f0000803f0000803f0000604000000000000000000000000000000000000000000000000000"
)


def _pack_cstring(path: str) -> bytes:
    raw = path.replace("\\", "/").encode("ascii") + b"\x00"
    return struct.pack("<I", len(raw)) + raw


def build_bgem(diffuse: str, normal: str) -> bytes:
    """Rebuild BGEM v2 with new diffuse/normal paths from the Porcupine layout."""
    tmpl = bytes.fromhex(_TEMPLATE_HEX)
    # Layout verified against Porcupine SkinTexture_01.BGEM (220 bytes):
    #   head (0x3F) | u32+diffuse\0 | mid(10) | u32+normal\0 | trailer
    head = tmpl[:0x3F]
    mid_flags = bytes.fromhex("01000000000100000000")
    trailer = bytes.fromhex(
        "01000000000000000000000000803f0000803f0000803f00006040"
        "00000000000000000000000000000000000000000000000000"
    )
    return head + _pack_cstring(diffuse) + mid_flags + _pack_cstring(normal) + trailer


def diffuse_path(stem: str) -> str:
    return f"{FACEDETAILS_DIR}/{stem}_d.dds"


def normal_path(stem: str) -> str:
    if stem in FACE_HAS_NORMAL:
        return f"{FACEDETAILS_DIR}/{stem}_n.dds"
    return DEFAULT_NORMAL


def write_bank_txt(path: Path) -> None:
    lines = [
        "# Slice H — vanilla FaceDetails face overlays for Wound Lab.",
        "# Applied via LooksMenu Overlays on FaceGen head slot (2).",
        "# Soft dep: LooksMenu.esp only (templates ship with PickmansWhisper.esp).",
        "# Order must match MCM iFaceLabTemplate:WoundLab stepper.",
        "# iFaceLabTemplate2:WoundLab is the same list with a leading \"(none)\" skip slot.",
        "# Regenerated by: python tools/build_face_overlays.py",
    ]
    lines.extend(FACE_BANK)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_overlays_json(path: Path) -> None:
    entries = []
    for i, stem in enumerate(FACE_BANK):
        entries.append(
            {
                "id": stem,
                "name": f"$PW Face {stem}",
                "slots": [
                    {
                        "slot": FACE_SLOT,
                        "material": f"overlays\\PickmansWhisper\\{stem}.bgem",
                    }
                ],
                "playable": True,
                "transformable": True,
                "sort": i,
                "gender": 1,
            }
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")


def write_materials(mat_dir: Path) -> None:
    mat_dir.mkdir(parents=True, exist_ok=True)
    for stem in FACE_BANK:
        bgem = build_bgem(diffuse_path(stem), normal_path(stem))
        (mat_dir / f"{stem}.bgem").write_bytes(bgem)


def main() -> int:
    bank = ROOT / "Data" / "PickmansWhisper" / "config" / "DecayFaceOverlays.txt"
    overlays = (
        ROOT
        / "Data"
        / "F4SE"
        / "Plugins"
        / "F4EE"
        / "Overlays"
        / "PickmansWhisper.esp"
        / "overlays.json"
    )
    mats = ROOT / "Data" / "Materials" / "overlays" / "PickmansWhisper"

    write_bank_txt(bank)
    write_overlays_json(overlays)
    write_materials(mats)

    # Sanity: regenerated BGEM must parse two path strings.
    sample = build_bgem(diffuse_path("Bruising01"), normal_path("Bruising01"))
    if b"Bruising01_d.dds" not in sample:
        raise SystemExit("ERROR: BGEM missing diffuse path")
    if b"BaseFemaleHead_n.dds" not in sample:
        raise SystemExit("ERROR: BGEM missing default normal path")

    print(f"OK: {len(FACE_BANK)} face overlays")
    print(f"  {bank.relative_to(ROOT)}")
    print(f"  {overlays.relative_to(ROOT)}")
    print(f"  {mats.relative_to(ROOT)} ({len(FACE_BANK)} .bgem)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
